#######################
#                     #
#     Definitions     #
#                     #
#######################

# all jobs are safe to interrupt
default:
  interruptible: true
  timeout: 3h


#speedup git on runners
variables:
  GIT_DEPTH: "10"
  GIT_SUBMODULE_STRATEGY: recursive



inkscape:windows:x64: &windows_job
  stage: build
  tags:
    - shared-windows
  retry: 2
  cache:
    key: "cache-windows"
    paths:
      - ccache
    when: always
  variables:
    MSYSTEM: MINGW64
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
    CCACHE_MAXSIZE: "2.0G"
    WINDEPS_ARCHIVE: msys64.7z
    WINDEPS_RELEASE_TAG: r230611.1
    WINDEPS_RELEASE_URL: https://gitlab.com/api/v4/projects/46763286/packages/generic/windeps/$WINDEPS_RELEASE_TAG/$WINDEPS_ARCHIVE
  script:
    - wget.exe --quiet --no-check-certificate $WINDEPS_RELEASE_URL
    - 7z x -oC:/ $WINDEPS_ARCHIVE
    - C:/msys64/msys2_shell.cmd -defterm -no-start -mingw64 -here -c "cmake -Bbuild -G Ninja -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DWITH_INTERNAL_CAIRO=OFF"
    - C:/msys64/msys2_shell.cmd -defterm -no-start -mingw64 -here -c "timeout -k 10s 70m ninja -C build"
    - 7z a build.7z build
    - C:/msys64/msys2_shell.cmd -defterm -no-start -mingw64 -here -c "ninja -C build dist-win-all"
  artifacts:
    paths:
      - build.7z
      - build/inkscape*.7z
      - build/inkscape*.exe
      - build/inkscape*.msi
